// Distills the judgment labels (scripts/judgment-labels.ts) into the
// judgment head: a taste-shaped net trained RankNet-style against the frozen
// grammar critic, shipped as the DEFAULT taste every listener starts from.
// Personal captures fine-tune on top of it. Deterministic.
//
//   npx tsx scripts/train-judgment.ts

import { writeFileSync } from "node:fs";
import {
  SONG_MOTIF_MOVE_ROOTS,
  createSeededSongMotifPlan,
  developSongMotifWalk,
} from "../src/song-motif-plan";
import {
  createTasteWeights,
  featurizeWalkNotes,
  flattenWalk,
  logitOfFeatures,
  trainTastePreferenceStep,
} from "../src/critic";
import { CRITIC_WEIGHTS } from "../src/critic-weights";
import { JUDGMENT_LABELS } from "./judgment-labels";
import { judgmentGoalForSeed } from "./judgment-shared";

function mulberry32(seedValue: number): () => number {
  let a = seedValue >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

interface PairExample {
  preferred: number[];
  other: number[];
}

function featuresFor(planSeed: number, walkSeed: number): number[] {
  const plan = createSeededSongMotifPlan(planSeed, judgmentGoalForSeed(planSeed));
  const roots = SONG_MOTIF_MOVE_ROOTS[plan.move];
  return featurizeWalkNotes(flattenWalk(developSongMotifWalk(plan, walkSeed)), roots);
}

function shuffle<T>(items: T[], rng: () => number): T[] {
  for (let i = items.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1));
    [items[i], items[j]] = [items[j]!, items[i]!];
  }
  return items;
}

function pairAccuracy(examples: readonly PairExample[], taste: ReturnType<typeof createTasteWeights>): number {
  let wins = 0;
  for (const example of examples) {
    const preferred = logitOfFeatures(example.preferred, CRITIC_WEIGHTS) + logitOfFeatures(example.preferred, taste);
    const other = logitOfFeatures(example.other, CRITIC_WEIGHTS) + logitOfFeatures(example.other, taste);
    if (preferred > other) wins += 1;
  }
  return wins / Math.max(1, examples.length);
}

function main(): void {
  const rng = mulberry32(0x1ab715);
  const examples: PairExample[] = JUDGMENT_LABELS.map((label) => {
    const a = featuresFor(label.planSeed, label.aSeed);
    const b = featuresFor(label.planSeed, label.bSeed);
    return label.preferred === "A" ? { preferred: a, other: b } : { preferred: b, other: a };
  });
  shuffle(examples, rng);
  const holdout = examples.slice(0, 30);
  const train = examples.slice(30);

  const grammarBaseline = pairAccuracy(examples, createTasteWeights());
  console.log(`grammar-only baseline on all pairs: ${grammarBaseline.toFixed(3)} (near-ties, so ~0.5 expected)`);

  const taste = createTasteWeights(0x4d9e);
  for (let epoch = 0; epoch < 80; epoch += 1) {
    for (const example of shuffle([...train], rng)) {
      trainTastePreferenceStep(taste, example.preferred, example.other, CRITIC_WEIGHTS, 0.05);
    }
    if (epoch % 20 === 19) {
      console.log(`epoch ${epoch + 1}: train ${pairAccuracy(train, taste).toFixed(3)} holdout ${pairAccuracy(holdout, taste).toFixed(3)}`);
    }
  }
  const trainAcc = pairAccuracy(train, taste);
  const holdoutAcc = pairAccuracy(holdout, taste);
  console.log(`final: train ${trainAcc.toFixed(3)} holdout ${holdoutAcc.toFixed(3)}`);
  if (holdoutAcc < 0.6) {
    throw new Error(`holdout pair accuracy ${holdoutAcc.toFixed(3)} below 0.6 — not shipping the judgment head`);
  }

  const round = (value: number) => Math.round(value * 1e6) / 1e6;
  const body = [
    'import type { CriticWeightsData } from "./critic";',
    "",
    "// Generated by scripts/train-judgment.ts — do not edit by hand.",
    "// The judgment head: Claude Fable 5's pairwise musical judgment over 150",
    "// near-decision development pairs, distilled into the taste-net shape and",
    "// shipped as the default taste. Personal captures fine-tune on top.",
    `// pair accuracy: train ${trainAcc.toFixed(3)}, holdout ${holdoutAcc.toFixed(3)} (grammar-only baseline ${grammarBaseline.toFixed(3)}).`,
    `export const CRITIC_JUDGMENT_WEIGHTS: CriticWeightsData = ${JSON.stringify(
      {
        version: "grow.criticJudgment/1",
        w1: taste.w1.map((row) => row.map(round)),
        b1: taste.b1.map(round),
        w2: taste.w2.map(round),
        b2: round(taste.b2),
        featureMeans: [...CRITIC_WEIGHTS.featureMeans],
      },
      null,
      2,
    )};`,
    "",
  ].join("\n");
  writeFileSync(new URL("../src/critic-judgment-weights.ts", import.meta.url), body);
  console.log("wrote src/critic-judgment-weights.ts");
}

main();
